import NavMenu from "@/components/NavMenu";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className="flex flex-col width-full min-h-screen"
        >
            <body
                className={`${inter.className} container fluid p-2 width-full`}
            >
                <NavMenu />
                {children}
            </body>
        </html>
    );
}
