create table "public"."jobPost" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "salaryMin" bigint,
    "salaryMax" bigint,
    "tags" character varying[],
    "description" text,
    "location" character varying,
    "companyName" character varying,
    "jobTitle" character varying
);


alter table "public"."jobPost" enable row level security;

CREATE UNIQUE INDEX "jobPost_pkey" ON public."jobPost" USING btree (id);

alter table "public"."jobPost" add constraint "jobPost_pkey" PRIMARY KEY using index "jobPost_pkey";

grant delete on table "public"."jobPost" to "anon";

grant insert on table "public"."jobPost" to "anon";

grant references on table "public"."jobPost" to "anon";

grant select on table "public"."jobPost" to "anon";

grant trigger on table "public"."jobPost" to "anon";

grant truncate on table "public"."jobPost" to "anon";

grant update on table "public"."jobPost" to "anon";

grant delete on table "public"."jobPost" to "authenticated";

grant insert on table "public"."jobPost" to "authenticated";

grant references on table "public"."jobPost" to "authenticated";

grant select on table "public"."jobPost" to "authenticated";

grant trigger on table "public"."jobPost" to "authenticated";

grant truncate on table "public"."jobPost" to "authenticated";

grant update on table "public"."jobPost" to "authenticated";

grant delete on table "public"."jobPost" to "service_role";

grant insert on table "public"."jobPost" to "service_role";

grant references on table "public"."jobPost" to "service_role";

grant select on table "public"."jobPost" to "service_role";

grant trigger on table "public"."jobPost" to "service_role";

grant truncate on table "public"."jobPost" to "service_role";

grant update on table "public"."jobPost" to "service_role";


