create table "public"."companies" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "website" character varying,
    "logo_url" character varying,
    "email" character varying not null,
    "description" text,
    "billing_email" character varying
);


alter table "public"."job_post" drop column "company_name";

alter table "public"."job_post" drop column "logo_path";

alter table "public"."job_post" add column "company_id" bigint;

CREATE UNIQUE INDEX "Companies_pkey" ON public.companies USING btree (id);

alter table "public"."companies" add constraint "Companies_pkey" PRIMARY KEY using index "Companies_pkey";

alter table "public"."job_post" add constraint "job_post_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."job_post" validate constraint "job_post_company_id_fkey";

grant delete on table "public"."companies" to "anon";

grant insert on table "public"."companies" to "anon";

grant references on table "public"."companies" to "anon";

grant select on table "public"."companies" to "anon";

grant trigger on table "public"."companies" to "anon";

grant truncate on table "public"."companies" to "anon";

grant update on table "public"."companies" to "anon";

grant delete on table "public"."companies" to "authenticated";

grant insert on table "public"."companies" to "authenticated";

grant references on table "public"."companies" to "authenticated";

grant select on table "public"."companies" to "authenticated";

grant trigger on table "public"."companies" to "authenticated";

grant truncate on table "public"."companies" to "authenticated";

grant update on table "public"."companies" to "authenticated";

grant delete on table "public"."companies" to "service_role";

grant insert on table "public"."companies" to "service_role";

grant references on table "public"."companies" to "service_role";

grant select on table "public"."companies" to "service_role";

grant trigger on table "public"."companies" to "service_role";

grant truncate on table "public"."companies" to "service_role";

grant update on table "public"."companies" to "service_role";


