revoke delete on table "public"."jobPost" from "anon";

revoke insert on table "public"."jobPost" from "anon";

revoke references on table "public"."jobPost" from "anon";

revoke select on table "public"."jobPost" from "anon";

revoke trigger on table "public"."jobPost" from "anon";

revoke truncate on table "public"."jobPost" from "anon";

revoke update on table "public"."jobPost" from "anon";

revoke delete on table "public"."jobPost" from "authenticated";

revoke insert on table "public"."jobPost" from "authenticated";

revoke references on table "public"."jobPost" from "authenticated";

revoke select on table "public"."jobPost" from "authenticated";

revoke trigger on table "public"."jobPost" from "authenticated";

revoke truncate on table "public"."jobPost" from "authenticated";

revoke update on table "public"."jobPost" from "authenticated";

revoke delete on table "public"."jobPost" from "service_role";

revoke insert on table "public"."jobPost" from "service_role";

revoke references on table "public"."jobPost" from "service_role";

revoke select on table "public"."jobPost" from "service_role";

revoke trigger on table "public"."jobPost" from "service_role";

revoke truncate on table "public"."jobPost" from "service_role";

revoke update on table "public"."jobPost" from "service_role";

alter table "public"."jobPost" drop constraint "jobPost_pkey";

drop index if exists "public"."jobPost_pkey";

drop table "public"."jobPost";

create table "public"."job_post" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "salary_min" bigint,
    "salary_max" bigint,
    "tags" character varying[],
    "description" text,
    "location" character varying,
    "company_name" character varying,
    "job_title" character varying
);


alter table "public"."job_post" enable row level security;

CREATE UNIQUE INDEX "jobPost_pkey" ON public.job_post USING btree (id);

alter table "public"."job_post" add constraint "jobPost_pkey" PRIMARY KEY using index "jobPost_pkey";

grant delete on table "public"."job_post" to "anon";

grant insert on table "public"."job_post" to "anon";

grant references on table "public"."job_post" to "anon";

grant select on table "public"."job_post" to "anon";

grant trigger on table "public"."job_post" to "anon";

grant truncate on table "public"."job_post" to "anon";

grant update on table "public"."job_post" to "anon";

grant delete on table "public"."job_post" to "authenticated";

grant insert on table "public"."job_post" to "authenticated";

grant references on table "public"."job_post" to "authenticated";

grant select on table "public"."job_post" to "authenticated";

grant trigger on table "public"."job_post" to "authenticated";

grant truncate on table "public"."job_post" to "authenticated";

grant update on table "public"."job_post" to "authenticated";

grant delete on table "public"."job_post" to "service_role";

grant insert on table "public"."job_post" to "service_role";

grant references on table "public"."job_post" to "service_role";

grant select on table "public"."job_post" to "service_role";

grant trigger on table "public"."job_post" to "service_role";

grant truncate on table "public"."job_post" to "service_role";

grant update on table "public"."job_post" to "service_role";


